addons:
  sonarcloud:
    organization: "mansinahar-github"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

language: go

go:
- 1.x
- "1.10"
- 1.11.x
- master
